---
- hosts: application
  become: yes
  gather_facts: no
  tasks:
  - name: starting nginx container
    docker_container:
      name: "{{ nginx_docker_name }}"
      image: "{{ nginx_docker_image }}"
      state: started
      recreate: yes
      pull: yes
      restart: yes
      hostname: "{{ inventory_hostname }}"
      restart_policy: unless-stopped
      ports:
         - 1234:80

